#!/usr/bin/env perl

use strict;
use warnings;

my @files = (".vimrc", ".eslintrc.json", ".gitconfig", ".tern-config",
  ".Xresources", ".ycm_extra_conf.py", ".zshrc", ".npmrc", ".oh-my-zsh", ".bashrc", ".bash_aliases");
my @vim_folders = ("swaps", "backups", "undo");
my @symlinks = (".config/nvim/init.vim", ".config/nvim");

sub dotfile_init {
  while (my $file = shift @files) {
    system("ln -s \$PWD/$file \$HOME/$file");
  }

  while (my $folder = shift @vim_folders) {
    system("mkdir -p \$HOME/.vim/$folder");
  }

  system("mkdir -p \$HOME/.vim \$HOME/.config");
  system("ln -s \$PWD/.bin \$HOME/");
  system("ln -s \$HOME/.vim \$HOME/.config/nvim");
  system("ln -s \$HOME/.vimrc \$HOME/.config/nvim/init.vim");
  system("ln -s \$PWD/.config/i3 \$HOME/.config/");
}

sub dotfile_remove {
  while (my $file = shift @files) {
    system("rm \$HOME/$file");
  }

  while (my $file = shift @symlinks) {
    system("rm \$HOME/$file");
  }
}

if (defined $ARGV[0] && shift eq "clean") {
  dotfile_remove();
  exit 0;
}

dotfile_init @ARGV;

